pretrain_model: './pretrain_model/resnet50.pth'
load_model: False
seed: 7
cuda_device: 3
model: 'SINet-V2'

data_path: '../new_data'
config_path: './config/config.yaml'
summary_path: './summary/summary.xlsx'
record_path: './record'
log_path: './log'
image_res_path: './image_res'
checkpoints_path: './checkpoints'

num_workers:
  train: 8
  test: 0
batch_size:
  train: 32
  test: 1
shuffle:
  train: True
  test: False
train_ratio: 0.8
test_ratio: 0.2

mean:
  R: 25.34
  G: 25.34
  B: 25.34
std:
  R: 51.11
  G: 51.11
  B: 51.11

size: 512
optimizer: 'SGD'
lr: 0.005
lr_schedure: 0.5
lr_step: 10
max_epoch: 85
weight_decay: 0.0005
momentum: 0.9
show_step: 20
